### ISSUE TITLE
EventBus address always get first one

### ISSUE THREAD

**Issue by leotu** [reactiverse/consul-cluster-manager#14]
I have three node( instance): 
172.25.130.241: 4600, 172.25.130.241: 4601, 172.25.130.241: 4602

and register:
eb.<String>consumer("abc-addr", ...)

each node fire event:
eb.request("abc-addr", data, ...)

but, it always the newest one process the message. (ie, 172.25.130.241: 4602)
i thank the "ChoosableIterable" implement class "ChoosableSet<T>" or "ConsulAsyncMultiMap"
should keep previous pointer or instance for Load-Balance chooser

**Comment by romalev** [comment]
@leotu - let me clarify something, so you have 3 nodes where every node is registered as a consumer under "abc-addr", and the same every node fires a message (ONLY ONCE) toward "abc-addr" - processing of those messages ends up on the ONLY ONE node. 

If this is the case -> given behavior seems to be correct. Normally round robin load balancing takes place on the "client node" (so the requester resolves the subscriber on the fly based on available list of subscribers.) If each of the requesters sends a message just once -> those messages will get processed by the node that gets resolved.

Now if you have a requester node sending multiple messages toward address "abc-addr" (and say you have multiple subscribers under "adc-addr") -> then normally you message should get balanced in dummy round robin fashion between subscribers.

I'll try to verify if load balancing is behaving as expected in this implementation as soon as I can and I'll get back to this.

**Comment by romalev** [comment]
@leotu , just FYI I've just released 1.2.2 (compatible with vert.x-core 3.8.2) which also included a bit enriched way of retrieving/resolving subscribers from consul (see #16 ). Can you please verify this issue with the new ([1.2.2](https://repo1.maven.org/maven2/io/reactiverse/consul-cluster-manager/1.2.2/)) version ? Looking forward seeing your results.

Thanks in advance!

**Comment by romalev** [comment]
Getting this one closed.
